#!/usr/bin/env python3
"""Extract the PROV-O terms FMO uses into a vendored subset.

Usage:
    curl -sSLo /tmp/prov-o.ttl https://www.w3.org/ns/prov-o-20130430.ttl
    python3 scripts/extract_prov_subset.py /tmp/prov-o.ttl

Writes src/imports/prov-subset.ttl. Do not hand-edit the output.

Only axioms among the kept terms survive. The property chains go, because they
point into the qualified pattern FMO does not use, and so does wasRevisionOf's
owl:AnnotationProperty typing, which would pun it and take the import out of OWL DL.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

from rdflib import Graph, Literal, Namespace, OWL, RDF, RDFS, URIRef, XSD

PROV = Namespace("http://www.w3.org/ns/prov#")
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "imports" / "prov-subset.ttl"
SOURCE = "https://www.w3.org/ns/prov-o-20130430.ttl"
# The W3C Recommendation is immutable in principle; the digest makes it so in practice.
SHA256 = "3d03c8e15753178541fb8cd59fbefecaf1861f9c37ef75190c6e938b85fb0c3d"

CLASSES = ["Entity", "Activity", "Agent", "SoftwareAgent"]
PROPERTIES = [
    "used", "wasGeneratedBy", "wasAssociatedWith", "wasAttributedTo",
    "wasDerivedFrom", "wasRevisionOf", "startedAtTime", "endedAtTime",
]
DECLARATIONS = {OWL.Class, OWL.ObjectProperty, OWL.DatatypeProperty}
AXIOMS = {RDFS.subClassOf, RDFS.subPropertyOf, RDFS.domain, RDFS.range, OWL.disjointWith}


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    path = Path(sys.argv[1])
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != SHA256:
        print(f"{path}: sha256 {digest}, expected {SHA256} for {SOURCE}", file=sys.stderr)
        return 1

    src = Graph().parse(path, format="turtle")
    kept = {PROV[t] for t in CLASSES + PROPERTIES}
    missing = sorted(str(t) for t in kept if (t, None, None) not in src)
    if missing:
        print("MISSING from PROV-O:\n  " + "\n  ".join(missing), file=sys.stderr)
        return 1

    out = Graph()
    out.bind("prov", PROV)
    for term in sorted(kept, key=str):
        for p, o in src.predicate_objects(term):
            if p == RDF.type and o in DECLARATIONS:
                out.add((term, p, o))
            elif p in (RDFS.label, RDFS.comment) and isinstance(o, Literal):
                out.add((term, p, o))
            elif p in AXIOMS and (o in kept or (isinstance(o, URIRef) and str(o).startswith(str(XSD)))):
                out.add((term, p, o))

    subset = URIRef("https://w3id.org/forecast-market-ontology/imports/prov-subset")
    out.add((subset, RDF.type, OWL.Ontology))
    out.add((subset, RDFS.label, Literal("PROV-O subset for FMO")))
    out.add((subset, RDFS.comment, Literal(
        f"Terms extracted from {SOURCE}. Generated by scripts/extract_prov_subset.py; do not hand-edit.")))

    header = f"""# PROV-O subset, extracted by scripts/extract_prov_subset.py -- DO NOT HAND-EDIT.
#
# {len(CLASSES)} classes and {len(PROPERTIES)} properties from {SOURCE}
# (sha256 {SHA256}). Regenerate with `make prov`.
#
# PROV-O is published by the W3C under the W3C Document License.

"""
    OUT.write_text(header + out.serialize(format="turtle"), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(out)} triples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
